// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardSizeSlider: typeof import('./components/CardSizeSlider.vue')['default']
    DragProvider: typeof import('./components/DragProvider.vue')['default']
    List: typeof import('./components/List.vue')['default']
    ListCard: typeof import('./components/ListCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NSlider: typeof import('naive-ui')['NSlider']
    NTimeline: typeof import('naive-ui')['NTimeline']
    NTimelineItem: typeof import('naive-ui')['NTimelineItem']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
    UploadProgress: typeof import('./components/UploadProgress.vue')['default']
  }
}
